name: Turtle Giant
favicon: null
layout_spectrum: 0.50904
typography_spectrum: 0.4105941958259791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1008'
    - '#060400'
    - '#1d1f10'
    - '#3a3923'
    - '#663e00'
  brandStrength: 0.5
  lightness: 0.35152600100263953
  saturation: 0.4895266455132514
  rhythmicContrast: 0.04602158674970269
purpose: []
